module.exports = {
  TOKEN: 'YOUR_BOT_TOKEN_HERE',
  SUPER_OWNER: 'YOUR_DISCORD_ID_HERE',
  LTC_ADDRESS: 'YOUR_LTC_ADDRESS_HERE',
  USDT_ADDRESS: 'YOUR_USDT_ADDRESS_HERE',
  TOS_CHANNEL_ID: 'YOUR_TOS_CHANNEL_ID_HERE',
  TICKET_CATEGORY_ID: 'YOUR_TICKET_CATEGORY_ID_HERE',
  SIMULATE_ROLE_ID: 'YOUR_SIMULATE_ROLE_ID_HERE',
  LOG_CHANNEL_ID: 'YOUR_LOG_CHANNEL_ID_HERE',
}
