module.exports = {
  TOKEN: 'YOUR_TOKEN_HERE',
  SUPER_OWNER: '1472661189824872622',
  LTC_ADDRESS: 'YOUR_LTC_ADDRESS_HERE',
  USDT_ADDRESS: 'YOUR_USDT_ADDRESS_HERE',
  TOS_CHANNEL_ID: 'YOUR_TOS_CHANNEL_ID_HERE',
  TICKET_CATEGORY_ID: 'YOUR_TICKET_CATEGORY_ID_HERE',
  SIMULATE_ROLE_ID: 'YOUR_SIMULATE_ROLE_ID_HERE',
  LOG_CHANNEL_ID: 'YOUR_LOG_CHANNEL_ID_HERE',
}
